version: '2.1'

services:
  app:
    build: .
    image: workshop
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: workshop
    ports:
      - '8080'

    # Example logging to logstash on Docker host
    #logging:
    #  driver: gelf
    #  options:
    #    # logstash is running on this address
    #    gelf-address: udp://127.0.0.1:12201


  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: workshop

    # Example logging to logstash on Docker host
    #logging:
    #  driver: gelf
    #  options:
    #    # logstash is running on this address
    #    gelf-address: udp://127.0.0.1:12201
